name: Afilo Shopify Next.js Code Review

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
  workflow_dispatch:

jobs:
  claude-afilo-review:
    runs-on: ubuntu-latest
    if: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Afilo Shopify + Next.js Code Review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          track_progress: true
          prompt: |
            **Afilo Project Context:**
            REPOSITORY: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            You are reviewing code for the Afilo e-commerce platform - a modern headless Shopify storefront.

            **Tech Stack:**
            - Frontend: Next.js 15.5.4 (App Router), TypeScript
            - Styling: Tailwind CSS v4 (no config file), ShadCN UI
            - Backend: Shopify (fzjdsw-ma.myshopify.com)
            - State: Zustand for cart management
            - Deployment: app.afilo.io (frontend), account.afilo.io (customer accounts)

            **Review Priorities:**
            1. **E-commerce Functionality**: Cart, checkout, product display
            2. **Shopify Integration**: API usage, data flow, error handling
            3. **Security**: Customer data protection, API token security
            4. **Performance**: Core Web Vitals, bundle optimization
            5. **Tailwind v4**: Proper usage without config file
            6. **TypeScript**: Strict typing for Shopify data
            7. **Brand Consistency**: Modern AI/software aesthetic

            Use the `@shopify-code-review` agent perspective for comprehensive analysis.
            Focus on e-commerce patterns and Afilo brand requirements.

            After analysis, use `gh pr comment` to post your review.

          claude_args: '--model claude-sonnet-4 --allowed-tools "Bash(gh pr comment:*),Bash(gh pr view:*),Bash(gh pr diff:*)"'

      - name: Design Review for UI Changes
        if: contains(github.event.pull_request.changed_files, '.tsx') || contains(github.event.pull_request.changed_files, 'globals.css')
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            **Afilo Design Review**

            Review UI/UX changes for the Afilo e-commerce platform.
            Focus on:
            - Conversion optimization for e-commerce
            - Tailwind v4 implementation (no config file)
            - ShadCN component usage
            - Mobile-first responsive design
            - Accessibility (WCAG 2.1 AA)
            - Afilo brand consistency (modern AI/software aesthetic)

            Use the `@nextjs-design-review` agent perspective.
            Post findings with `gh pr comment` if issues found.

          claude_args: '--model claude-sonnet-4 --allowed-tools "Bash(gh pr comment:*)"'

      - name: Security Review for E-commerce Changes
        if: contains(github.event.pull_request.changed_files, 'lib/') || contains(github.event.pull_request.changed_files, 'app/api/') || contains(github.event.pull_request.changed_files, 'store/')
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            **Afilo Security Review**

            Security review for changes affecting:
            - Shopify API integration (fzjdsw-ma.myshopify.com)
            - Customer data handling (account.afilo.io)
            - Cart security and state management
            - Payment flow security
            - Environment variable usage

            Use the `@ecommerce-security-review` agent.
            Only report high-confidence security vulnerabilities.
            Post findings with `gh pr comment` if critical issues found.

          claude_args: '--model claude-sonnet-4 --allowed-tools "Bash(gh pr comment:*)"'
